apiVersion: v1
kind: ConfigMap
metadata:
  name: ghr-config
  labels:
    {{- include "ghr.labels" . | nindent 4 }}
data:
  REPO_OWNER: {{ .Values.ghr.repo_owner }}
  REPO_NAME: {{ .Values.ghr.repo_name }}
  REPO_URL: {{ .Values.ghr.repo_url }}
  ACTIONS_RUNNER_INPUT_URL: {{ .Values.ghr.repo_url }}
