apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghr.fullname" . }}
  labels:
    {{- include "ghr.labels" . | nindent 4 }}
type: Opaque
data:
  url: {{ .Values.ghr.url }}
  token: {{ .Values.ghr.token }}
  pool: {{ .Values.ghr.pool }}
